monitor_mic: true
monitor_asr: true
model_path: 'models/kaldi-models/vosk-model-de-0.21'
vosk:
  language: de
  #model_path: './vosk-model-de-tuda-0.6-900k'
  pipeline: 'pulsesrc ! audio/x-raw,format=S16LE,channels=6,rate={} ! deinterleave name=d d.src_0 ! appsink name=sink emit-signals=true'

vad:
  threshold: 0.3
  min_silence_duration_ms: 300
